// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxgludnrxdubafwnalxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4Z2x1ZG5yeGR1YmFmd25hbHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTg4MDUsImV4cCI6MjA2MDEzNDgwNX0.t1e-m7mUfAcpfP8JqQRSyovi7IAO80xP0D-oAX18tWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);